### ISSUE TITLE
no version number on macOS

### ISSUE THREAD

**Issue by core-code** [pgc062020/DailyDesktopWallpaperPlus_macOS#1]
i've downloaded version 1.4 but when selecting it in the Finder it doesn't have a  version number

the CFBundleShortVersionString and CFBundleVersion entries in your Info.plist file are missing

<img width="260" alt="Screenshot 2020-10-07 at 11 38 20" src="https://user-images.githubusercontent.com/1261954/95314550-bbdc7700-0891-11eb-85a3-24fd272df878.png">

**Comment by pgc062020** [comment]
Thank you for bringing this to my attention.
I will fix this with the next software release.

Kind regards

**Comment by pgc062020** [comment]
> i've downloaded version 1.4 but when selecting it in the Finder it doesn't have a version number
> 
> the CFBundleShortVersionString and CFBundleVersion entries in your Info.plist file are missing
> 
> <img alt="Screenshot 2020-10-07 at 11 38 20" width="260" src="https://user-images.githubusercontent.com/1261954/95314550-bbdc7700-0891-11eb-85a3-24fd272df878.png">

Thank you for bringing this to my attention.
I will fix this with the next software release.

Kind regards

**Comment by pgc062020** [comment]
> i've downloaded version 1.4 but when selecting it in the Finder it doesn't have a version number
> 
> the CFBundleShortVersionString and CFBundleVersion entries in your Info.plist file are missing
> 
> <img alt="Screenshot 2020-10-07 at 11 38 20" width="260" src="https://user-images.githubusercontent.com/1261954/95314550-bbdc7700-0891-11eb-85a3-24fd272df878.png">

I've the new version 1.5 released of DailyDesktopWallpaperPlus now.

Kind regards

**Comment by core-code** [comment]
awesome thanks i can confirm it is fixed
