### ISSUE TITLE
Add support for UHD images

### ISSUE THREAD

**Issue by esmcelroy** [pgc062020/DailyDesktopWallpaperPlus_macOS#3]
Hey! Love the app idea and the implementation - it's something I've wanted to set up for a long time. 

I'm currently using the version from the [SourceForge ticket]( https://sourceforge.net/p/dailydesktopwallpaperplus/tickets/1/), with the contributions from @jimiatnymbl and based on issue #2 

One request - would it be possible to also offer the UHD picture version (when available)?
I did some light poking around of the Bing Wallpaper API, and it looks like the UHD version URL looks like this example: https://www.bing.com//th?id=OHR.DiamondBeach_EN-CA1051338590_UHD.jpg - where instead of using the resolution, it uses **UHD**. If I had access to the source of Jimi's version ("1.8"), I'd probably toy around with it to see if I could add it myself, but I do not. 

Any help would be appreciated! 

Cheers!

**Comment by jimiatnymbl** [comment]
I've offered to submit a Pull Request but haven't heard back.  I can either Fork (not my preference) or post the source here as a zip file.

**Comment by esmcelroy** [comment]
Also, based on my very minimal research on the matter, it appears that the UHD version is always the highest resolution version of the image available. 
E.g. https://bing.com/th?id=OHR.LargestCave_EN-CA2461053607_UHD.jpg and https://bing.com/th?id=OHR.YukonClouds_EN-CA8734704541_UHD.jpg 

The former is about 6Kx4K and the latter is 1080p. So, assuming that if one of the resolution options is just UHD and you use that in lieu of a resolution, it should work.

**Comment by esmcelroy** [comment]
> I've offered to submit a Pull Request but haven't heard back. I can either Fork (not my preference) or post the source here as a zip file.

I'd be happy to take a look and give it a try to update, but maybe we'll wait for @pgc062020 to respond. It doesn't appear to be a major change, but I'd want your updates as well.

**Comment by pgc062020** [comment]
Hi  esmcelroy

Thank you much for your suggestion and for this hint! 
I didn't know the Bing images were available in UHD. 
I'm currently working on a major update.
I will add the UHD option for the Bing-Wallpapers with this resolution into the app. 
Maybe UHD wallpapers are also available from the Windows Spotlight provider.
I'll let you know when I've finished the new version of the App.

Cheers

**Comment by pgc062020** [comment]
> I've offered to submit a Pull Request but haven't heard back. I can either Fork (not my preference) or post the source here as a zip file.

I have now answered you.
https://sourceforge.net/p/dailydesktopwallpaperplus/tickets/1/#7d16/8396/40a1/cfaa/bc8e

Cheers

**Comment by pgc062020** [comment]
> Also, based on my very minimal research on the matter, it appears that the UHD version is always the highest resolution version of the image available.
> E.g. https://bing.com/th?id=OHR.LargestCave_EN-CA2461053607_UHD.jpg and https://bing.com/th?id=OHR.YukonClouds_EN-CA8734704541_UHD.jpg
> 
> The former is about 6Kx4K and the latter is 1080p. So, assuming that if one of the resolution options is just UHD and you use that in lieu of a resolution, it should work.

If I open the image on Bing as (with "UHD" in the url ") then there is a problem:
Not every photo corresponds to the UHD resolution.
There are photos that are only 1920 x 1080 pixels (which Bing defines as "UHD").
But I will nevertheless integrate the UHD option into the new software version.

**Comment by pgc062020** [comment]
Hi All,

I just uploaded a new release (v2.0) of the DDWP source code on GitHub.

This release allows to download photos those higher than 1920x1200. 
Pictures with UHD size are included.

Have fun!
